// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    user_id,
    total_amount
) VALUES ($1, $2)
RETURNING id, user_id, status, total_amount, created_at, updated_at
`

type CreateOrderParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	TotalAmount int64       `json:"total_amount"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.TotalAmount)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id,
    product_id,
    quantity,
    price,
    subtotal
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, product_id, quantity, price, subtotal, created_at, updated_at
`

type CreateOrderItemParams struct {
	OrderID   pgtype.UUID `json:"order_id"`
	ProductID pgtype.UUID `json:"product_id"`
	Quantity  int32       `json:"quantity"`
	Price     int64       `json:"price"`
	Subtotal  int64       `json:"subtotal"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
		arg.Subtotal,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
		&i.Subtotal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    order_id,
    amount,
    provider,
    transaction_id
) VALUES ($1, $2, $3, $4)
RETURNING id, order_id, amount, status, provider, transaction_id, created_at, updated_at
`

type CreatePaymentParams struct {
	OrderID       pgtype.UUID `json:"order_id"`
	Amount        int64       `json:"amount"`
	Provider      string      `json:"provider"`
	TransactionID pgtype.Text `json:"transaction_id"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.Amount,
		arg.Provider,
		arg.TransactionID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Status,
		&i.Provider,
		&i.TransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decreaseProductStock = `-- name: DecreaseProductStock :execrows
UPDATE products
SET stock = stock - $1,
    updated_at = now()
WHERE id = $2
    AND stock >= $1
`

type DecreaseProductStockParams struct {
	Stock int32       `json:"stock"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) DecreaseProductStock(ctx context.Context, arg DecreaseProductStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, decreaseProductStock, arg.Stock, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockProductForUpdate = `-- name: LockProductForUpdate :one
SELECT id, name, description, price, stock, created_at, updated_at FROM products
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockProductForUpdate(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, lockProductForUpdate, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
