// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT p.id, p.order_id, p.amount, p.status, p.provider, p.transaction_id, p.created_at, p.updated_at FROM payments p
JOIN orders o ON o.id = p.order_id
WHERE o.id = $1
    AND o.user_id = $2
`

type GetPaymentByOrderIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetPaymentByOrderID(ctx context.Context, arg GetPaymentByOrderIDParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrderID, arg.ID, arg.UserID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Status,
		&i.Provider,
		&i.TransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockOrderForPayment = `-- name: LockOrderForPayment :one
SELECT id, user_id, status, total_amount, created_at, updated_at FROM orders
WHERE id = $1
    AND user_id = $2
FOR UPDATE
`

type LockOrderForPaymentParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) LockOrderForPayment(ctx context.Context, arg LockOrderForPaymentParams) (Order, error) {
	row := q.db.QueryRow(ctx, lockOrderForPayment, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockPaymentForUpdate = `-- name: LockPaymentForUpdate :one
SELECT id, order_id, amount, status, provider, transaction_id, created_at, updated_at FROM payments
WHERE order_id = $1
FOR UPDATE
`

func (q *Queries) LockPaymentForUpdate(ctx context.Context, orderID pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, lockPaymentForUpdate, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Status,
		&i.Provider,
		&i.TransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOrderAsPaid = `-- name: MarkOrderAsPaid :one
UPDATE orders
SET status = 'paid',
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, status, total_amount, created_at, updated_at
`

func (q *Queries) MarkOrderAsPaid(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, markOrderAsPaid, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $1,
    transaction_id = $2,
    updated_at = now()
WHERE order_id = $3
RETURNING id, order_id, amount, status, provider, transaction_id, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	Status        string      `json:"status"`
	TransactionID pgtype.Text `json:"transaction_id"`
	OrderID       pgtype.UUID `json:"order_id"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.Status, arg.TransactionID, arg.OrderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Status,
		&i.Provider,
		&i.TransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
