// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdempotency = `-- name: CreateIdempotency :one
INSERT INTO idempotency_keys (
    key,
    user_id,
    request_hash
) VALUES ($1, $2, $3)
ON CONFLICT (key) DO NOTHING
RETURNING key, user_id, request_hash, response, created_at, updated_at
`

type CreateIdempotencyParams struct {
	Key         string      `json:"key"`
	UserID      pgtype.UUID `json:"user_id"`
	RequestHash string      `json:"request_hash"`
}

func (q *Queries) CreateIdempotency(ctx context.Context, arg CreateIdempotencyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotency, arg.Key, arg.UserID, arg.RequestHash)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.UserID,
		&i.RequestHash,
		&i.Response,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdempotencyByUserID = `-- name: GetIdempotencyByUserID :one
SELECT key, user_id, request_hash, response, created_at, updated_at FROM idempotency_keys
WHERE key = $1
    AND user_id = $2
`

type GetIdempotencyByUserIDParams struct {
	Key    string      `json:"key"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetIdempotencyByUserID(ctx context.Context, arg GetIdempotencyByUserIDParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyByUserID, arg.Key, arg.UserID)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.UserID,
		&i.RequestHash,
		&i.Response,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reclaimStaleIdempotency = `-- name: ReclaimStaleIdempotency :one
UPDATE idempotency_keys
SET request_hash = $1,
    created_at = now(),
    updated_at = now()
WHERE key = $2
    AND user_id = $3
    AND response IS NULL
    AND created_at < $4
RETURNING key, user_id, request_hash, response, created_at, updated_at
`

type ReclaimStaleIdempotencyParams struct {
	RequestHash string             `json:"request_hash"`
	Key         string             `json:"key"`
	UserID      pgtype.UUID        `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ReclaimStaleIdempotency(ctx context.Context, arg ReclaimStaleIdempotencyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, reclaimStaleIdempotency,
		arg.RequestHash,
		arg.Key,
		arg.UserID,
		arg.CreatedAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.UserID,
		&i.RequestHash,
		&i.Response,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIdempotency = `-- name: UpdateIdempotency :one
UPDATE idempotency_keys
SET response = $1,
    updated_at = now()
WHERE key = $2
    AND user_id = $3
RETURNING key, user_id, request_hash, response, created_at, updated_at
`

type UpdateIdempotencyParams struct {
	Response []byte      `json:"response"`
	Key      string      `json:"key"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateIdempotency(ctx context.Context, arg UpdateIdempotencyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, updateIdempotency, arg.Response, arg.Key, arg.UserID)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.UserID,
		&i.RequestHash,
		&i.Response,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
